language: go

go: "1.11"

before_install:
  - go get github.com/mattn/goveralls
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

before_script:
  - mkdir -p /home/travis/.cache/thermoPi/
  - touch /home/travis/.cache/thermoPi/thermoPi.log
  - mkdir -p /home/travis/.config/thermoPi/
  - cp sample.toml /home/travis/.config/thermoPi/thermoPi.conf

script: 
  - go test -v ./...
  - $GOPATH/bin/goveralls -service=travis-ci
