FORMAT: 1A

# ThermoPi

This is the API documentation for ThermoPi's REST backend.

## Target Temperature [/target]

### View the Current Target [GET]

+ Response 200 (application/json)

        {
            "value":25
        }

### Set a New Target [POST]

+ Request (application/json)

        {
            "value":25,
            "persistent":true
        }

+ Response 201

## All Sensor Readings [/sensors]

### List the Current Sensor Readings [GET]

+ Response 200 (application/json)

        [
            {
                "name":"Bedroom",
                "value":23
            },
            {
                "name":"Kitchen",
                "value":30
            }
        ]

## Specific Sensor Readings [/sensors/{id}]

### View the Current Reading of a Sensor [GET]

+ Response 200 (application/json)

        {
            "value":22
        }

### Set the Current Reading of a Sensor [POST]

Note: This method of sending temperature readings is deprecated, please use the MQTT API instead.

+ Request (application/json)

        {
            "permanent":false,
            "target":23
        }